
OPT=

cmd=time ../bin/cic


tech=../examples/freepdk45.json

device: 
	${cmd}   ../examples/devices.json ${tech}  ${OPT}

sar:
	${cmd}   ../../cnano/examples/SAR_LPWR_ST28N/SAR_LPWR_ST28N.json ${tech} ${OPT}
