

test:
	../../bin/cic ../../examples/routes.json ../../examples/tech.json routes
	cicpy svg routes.cic ../../examples/tech_svg.json routes --x 100 --y 200

clean:
	rm -f routes.cic
	rm -rf routes_svg
	rm -f routes_svg.html
