name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: wulffern/aicex:22.04_0.1.3
      options: --user aicex
    steps:
    - name: ciccreator
      uses: actions/checkout@v2
    - name: Compile
      run: |
        sudo git config --global --add safe.directory /__w/ciccreator/ciccreator
        make
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag cic_qt_bionic:$(date +%s)
