name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          cache-dependency-path: docs/pdm.lock
          python-version-file: docs/pyproject.toml

      - name: Set up PDM
        run: pdm install -p docs

      - name: Install debian requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen texlive-font-utils

      - name: run doxygen
        run: doxygen

      - name: Sphinx build
        run: pdm run -p docs sphinx-build docs/source _build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
